### ISSUE TITLE
Content options

### ISSUE THREAD

**Issue by rodleviton** [swanky-docs/swanky-webpack-plugin#21]
@uglow currently the `content` key per page accepts the following:

- string path to file
- glob pattern to match multiple files
- url (external source)

I would like to see the option for the `content` key to take an array of content sources. This will allow more fine grained control over how pages are constructed. I am thinking something like this:

```
sections:
  - title: Foundation
    content: 
          - title: section 1
             path: 'some/path.md'

          - title: section 2
             path: 'some/other/glob/*.js'
             processor: ngdocs

         - title: section 3
             path: 'http://external.url'
```

All content would be rendered on single page in array order and allow a processor key per item.
